### PR TITLE
Update go versions, base image, module name, k8s.io deps

### LINKED ISSUE #78: Dump commands do not produce valid yaml documents
Running a dump yields the following:

```console
go run main.go --dump uwu-tools --github-token-path ~/.github-token | tee uwu-tools.yaml
```

```json
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"Throttle(300, 100, *)","severity":"info","time":"2022-07-06T07:24:29-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetOrg(uwu-tools)","severity":"info","time":"2022-07-06T07:24:29-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"User()","severity":"info","time":"2022-07-06T07:24:29-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListOrgMembers(uwu-tools, admin)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListOrgMembers(uwu-tools, member)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeams(uwu-tools)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetRepos(uwu-tools, false)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetRepo(uwu-tools, go-ghcrawl)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"component":"unset","file":"/Users/augustus/prj/relengfam/peribolos/cmd/main.go:84","func":"github.com/relengfam/peribolos/cmd.rootCmd","level":"info","msg":"Dumping orgs[\"uwu-tools\"]:","severity":"info","time":"2022-07-06T07:24:30-04:00"}
```

```yaml
admins:
- auggie-bot
- justaugustus
- sethmccombs
billing_email: ***@example.com
company: ""
default_repository_permission: read
description: ""
email: ""
has_organization_projects: true
has_repository_projects: true
location: ""
members_can_create_repositories: true
name: ""
repos:
  go-ghcrawl:
    default_branch: main
    has_projects: true
```

---

Now, let's try a `merge`:

```console
./admin/update.sh --github-token-path ~/.github-token
```

```console
+++ dirname ./admin/update.sh
++ cd ./admin/..
++ pwd -P
+ REPO_ROOT=/Users/augustus/prj/relengfam/peribolos
+ readonly REPO_ROOT
+ admins=('cpanato' 'justaugustus')
+ readonly admins
+ cd /Users/augustus/prj/relengfam/peribolos
+ make update-prep
cat: imagerefs: No such file or directory
make: Circular merge <- merge dependency dropped.
mkdir -p "/Users/augustus/prj/relengfam/peribolos/_output"
/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos merge \
		--merge-teams \
		--org-part=uwu-tools=config/uwu-tools/org.yaml \
		> /Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml
+ cmd=/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos
+ args=(--config-path="${REPO_ROOT}/_output/gen-config.yaml" --fix-org --fix-org-members --fix-teams --fix-team-members "${admins[@]/#/--required-admins=}")
+ /Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos --config-path=/Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml --fix-org --fix-org-members --fix-teams --fix-team-members --required-admins=cpanato --required-admins=justaugustus --github-token-path /Users/augustus/.github-token
{}
```

```json
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20211221011455-3d87616db8ae/prow/github/client.go:889","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"Throttle(300, 100, *)","severity":"info","time":"2022-07-06T07:35:05-04:00"}
{"component":"unset","file":"/Users/augustus/prj/relengfam/peribolos/cmd/main.go:106","func":"github.com/relengfam/peribolos/cmd.rootCmd","level":"info","msg":"Finished syncing configuration.","severity":"info","time":"2022-07-06T07:35:05-04:00"}
```

Let's look at the output:

```console
❯ cat _output/gen-config.yaml
```

_output/gen-config.yaml:

```yaml
{}

orgs:
  uwu-tools:
    admins:
    - auggie-bot
    - cpanato
    - justaugustus
    - sethmccombs
    billing_email: ***@example.com
    company: ""
    default_repository_permission: read
    description: ""
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    location: ""
    members_can_create_repositories: true
    name: ""
    repos:
      go-ghcrawl:
        default_branch: main
        has_projects: true
```

The above file is not a valid yaml document.

Note the following at the top of the file:

```yaml
{}

```

Note the same when using the `--help` flag:

```console
./admin/update.sh --github-token-path ~/.github-token --help
+++ dirname ./admin/update.sh
++ cd ./admin/..
++ pwd -P
+ REPO_ROOT=/Users/augustus/prj/relengfam/peribolos
+ readonly REPO_ROOT
+ admins=('cpanato' 'justaugustus')
+ readonly admins
+ cd /Users/augustus/prj/relengfam/peribolos
+ make update-prep
cat: imagerefs: No such file or directory
make: Circular merge <- merge dependency dropped.
mkdir -p "/Users/augustus/prj/relengfam/peribolos/_output"
/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos merge \
		--merge-teams \
		--org-part=uwu-tools=config/uwu-tools/org.yaml \
		> /Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml
+ cmd=/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos
+ args=(--config-path="${REPO_ROOT}/_output/gen-config.yaml" --fix-org --fix-org-members --fix-teams --fix-team-members "${admins[@]/#/--required-admins=}")
+ /Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos --config-path=/Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml --fix-org --fix-org-members --fix-teams --fix-team-members --required-admins=cpanato --required-admins=justaugustus --github-token-path /Users/augustus/.github-token --help
{}

Usage:
   [flags]
   [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  merge
  version     Prints the version

Flags:
      --allow-repo-archival                      If set, archiving repos is allowed while updating repos
      --allow-repo-publish                       If set, making private repos public is allowed while updating repos
      --config-path string                       Path to org config.yaml
      --confirm                                  Mutate github if set

<snip>

Use " [command] --help" for more information about a command.
```

### PR DESCRIPTION
**Pull request by cpanato**
when running the merge part

```
$ ./admin/update.sh --github-token-path .github-token
+++ dirname ./admin/update.sh
++ cd ./admin/..
++ pwd -P
+ REPO_ROOT=/Users/cpanato/code/src/github.com/uwu-tools/peribolos
+ readonly REPO_ROOT
+ admins=('cpanato' 'justaugustus' 'auggie-bot' 'sethmccombs')
+ readonly admins
+ cd /Users/cpanato/code/src/github.com/uwu-tools/peribolos
+ make update-prep
make: Circular merge <- merge dependency dropped.
mkdir -p "/Users/cpanato/code/src/github.com/uwu-tools/peribolos/_output"
/Users/cpanato/code/src/github.com/uwu-tools/peribolos/_output/bin/peribolos merge \
                --merge-teams \
                --org-part=uwu-tools=config/uwu-tools/org.yaml \
                > /Users/cpanato/code/src/github.com/uwu-tools/peribolos/_output/gen-config.yaml
+ cmd=/Users/cpanato/code/src/github.com/uwu-tools/peribolos/_output/bin/peribolos
+ args=(--config-path="${REPO_ROOT}/_output/gen-config.yaml" --fix-org --fix-org-members --fix-teams --fix-team-members "${admins[@]/#/--required-admins=}")
+ /Users/cpanato/code/src/github.com/uwu-tools/peribolos/_output/bin/peribolos --config-path=/Users/cpanato/code/src/github.com/uwu-tools/peribolos/_output/gen-config.yaml --fix-org --fix-org-members --fix-teams --fix-team-members --required-admins=cpanato --required-admins=justaugustus --required-admins=auggie-bot --required-admins=sethmccombs --github-token-path .github-token
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"Throttle(300, 100, *)","severity":"info","time":"2023-01-29T16:04:55+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetOrg(uwu-tools)","severity":"info","time":"2023-01-29T16:04:55+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:55+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListOrgInvitations(uwu-tools)","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"User()","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListOrgMembers(uwu-tools, admin)","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListOrgMembers(uwu-tools, member)","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:56+01:00"}
{"component":"unset","file":"/Users/cpanato/code/src/github.com/uwu-tools/peribolos/org/org.go:53","func":"github.com/uwu-tools/peribolos/org.Configure","level":"info","msg":"Skipping org repositories configuration","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeams(uwu-tools)","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeamMembersBySlug(uwu-tools, gh-jira-issue-sync-admins, member)","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeamMembersBySlug(uwu-tools, gh-jira-issue-sync-admins, maintainer)","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeamInvitationsBySlug(uwu-tools, gh-jira-issue-sync-admins)","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:57+01:00"}
{"component":"unset","file":"/Users/cpanato/code/src/github.com/uwu-tools/peribolos/org/org.go:76","func":"github.com/uwu-tools/peribolos/org.Configure","level":"info","msg":"Skipping team repo permissions configuration","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeamMembersBySlug(uwu-tools, gh-jira-issue-sync-maintainers, member)","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeamMembersBySlug(uwu-tools, gh-jira-issue-sync-maintainers, maintainer)","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeamInvitationsBySlug(uwu-tools, gh-jira-issue-sync-maintainers)","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"client":"github","component":"unset","file":"/Users/cpanato/code/pkg/mod/k8s.io/test-infra@v0.0.0-20230116172652-b51567b824d9/prow/github/client.go:1191","func":"k8s.io/test-infra/prow/github.(*client).doRequest","level":"info","msg":"Using GitHub REST API Version: 2022-11-28","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"component":"unset","file":"/Users/cpanato/code/src/github.com/uwu-tools/peribolos/org/org.go:76","func":"github.com/uwu-tools/peribolos/org.Configure","level":"info","msg":"Skipping team repo permissions configuration","severity":"info","time":"2023-01-29T16:04:58+01:00"}
{"component":"unset","file":"/Users/cpanato/code/src/github.com/uwu-tools/peribolos/cmd/main.go:107","func":"github.com/uwu-tools/peribolos/cmd.rootCmd","level":"info","msg":"Finished syncing configuration.","severity":"info","time":"2023-01-29T16:04:58+01:00"}
```

Partially addresses: https://github.com/uwu-tools/peribolos/issues/78

### CODE REVIEW

**Comment by cpanato** [comment]
@justaugustus can you review or can we merge this and follow up if needed?

**Review by justaugustus — APPROVED** [review]
@cpanato -- This doesn't quite fix the dump problems from https://github.com/uwu-tools/peribolos/issues/78, but there are lots of good fixes in here.

I separated the formatting changes and k8s.io dep bumps into separate commits.
I've also change the "test" org from `uwu-tools` to `relengfam`, since `uwu-tools` is now the "production" org.

Thanks!

**Comment by cpanato** [comment]
Ok i will take another look @justaugustus

**Comment by justaugustus** [comment]
> Ok i will take another look @justaugustus

Sounds good, thanks!
Take a peek at the sample commands in that bug filed and see if you're seeing the same outputs on your side.

**Pull request merged**
